/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quizmaster;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;

/**
 *
 * @author Asif & Noman
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        jTextFieldEnterName.setBackground(new java.awt.Color(0,0,0,1));
        jButtonExit.setBackground(new java.awt.Color(0,0,0,1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextFieldEnterName = new javax.swing.JTextField();
        jButtonTakeChallenge = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Enter Your Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 180, 220, 40));

        jTextFieldEnterName.setFont(new java.awt.Font("Algerian", 3, 18)); // NOI18N
        jTextFieldEnterName.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldEnterName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldEnterName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jTextFieldEnterName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEnterNameActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldEnterName, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 230, 300, 40));

        jButtonTakeChallenge.setBackground(new java.awt.Color(102, 0, 102));
        jButtonTakeChallenge.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonTakeChallenge.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTakeChallenge.setText("Take Challenge!");
        jButtonTakeChallenge.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        jButtonTakeChallenge.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonTakeChallenge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTakeChallengeActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTakeChallenge, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 200, 40));

        jButtonExit.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jButtonExit.setForeground(new java.awt.Color(153, 0, 153));
        jButtonExit.setText("EXIT");
        jButtonExit.setBorder(null);
        jButtonExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 110, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizmaster/background.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldEnterNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEnterNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEnterNameActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        //Sound
        try {
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File("src\\quizmaster\\click.wav").getAbsoluteFile());
            Clip clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();
        } catch (IOException | LineUnavailableException | UnsupportedAudioFileException ex) {
            System.out.println("Error playing sound file: " + ex.getMessage());
        }
        
        System.exit(0);
        
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonTakeChallengeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTakeChallengeActionPerformed
        
        
        if(!jTextFieldEnterName.getText().isEmpty()){
            
            try {
                AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File("src\\quizmaster\\click.wav").getAbsoluteFile());
                Clip clip = AudioSystem.getClip();
                clip.open(audioInputStream);
                clip.start();
            } catch (IOException | LineUnavailableException | UnsupportedAudioFileException ex) {
                System.out.println("Error playing sound file: " + ex.getMessage());
            }
            
            
            dispose();
            Topics topics = new Topics();
            topics.setVisible(true);
            
        }
        
        else{
        
            try {
                AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File("src\\quizmaster\\error.wav").getAbsoluteFile());
                Clip clip = AudioSystem.getClip();
                clip.open(audioInputStream);
                clip.start();
            } catch (IOException | LineUnavailableException | UnsupportedAudioFileException ex) {
                System.out.println("Error playing sound file: " + ex.getMessage());
            }
        
        }
        
        
    }//GEN-LAST:event_jButtonTakeChallengeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonTakeChallenge;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextFieldEnterName;
    // End of variables declaration//GEN-END:variables
}
