/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quizmaster;

import java.io.File;
import java.io.IOException;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;

/**
 *
 * @author asifa
 */
public class Sports extends javax.swing.JFrame {

    /**
     * Creates new form Sports
     */
    public Sports() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButtonCricket = new javax.swing.JButton();
        jButtonFootball = new javax.swing.JButton();
        jButtonTennis = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Select  a  sport");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 410, 30));

        jButtonCricket.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButtonCricket.setForeground(new java.awt.Color(102, 0, 102));
        jButtonCricket.setText("Cricket");
        jButtonCricket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCricketActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCricket, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 170, 30));

        jButtonFootball.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButtonFootball.setForeground(new java.awt.Color(102, 0, 102));
        jButtonFootball.setText("Football");
        jButtonFootball.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFootballActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFootball, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 170, 30));

        jButtonTennis.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButtonTennis.setForeground(new java.awt.Color(102, 0, 102));
        jButtonTennis.setText("Tennis");
        jButtonTennis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTennisActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTennis, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 170, 30));

        jButtonBack.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(153, 0, 153));
        jButtonBack.setText("BACK");
        jButtonBack.setBorder(null);
        jButtonBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 110, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizmaster/background.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCricketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCricketActionPerformed

        try {
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File("src\\quizmaster\\click.wav").getAbsoluteFile());
            Clip clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();
        } catch (IOException | LineUnavailableException | UnsupportedAudioFileException ex) {
            System.out.println("Error playing sound file: " + ex.getMessage());
        }
        
        dispose();
        SportsQuizCricket cricket = new SportsQuizCricket();
        cricket.setVisible(true);

    }//GEN-LAST:event_jButtonCricketActionPerformed

    private void jButtonFootballActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFootballActionPerformed

        try {
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File("src\\quizmaster\\click.wav").getAbsoluteFile());
            Clip clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();
        } catch (IOException | LineUnavailableException | UnsupportedAudioFileException ex) {
            System.out.println("Error playing sound file: " + ex.getMessage());
        }
        
        dispose();
        SportsQuizFootball football = new SportsQuizFootball();
        football.setVisible(true);

    }//GEN-LAST:event_jButtonFootballActionPerformed

    private void jButtonTennisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTennisActionPerformed

        try {
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File("src\\quizmaster\\click.wav").getAbsoluteFile());
            Clip clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();
        } catch (IOException | LineUnavailableException | UnsupportedAudioFileException ex) {
            System.out.println("Error playing sound file: " + ex.getMessage());
        }
        
        dispose();
        SportsQuizTennis tennis = new SportsQuizTennis();
        tennis.setVisible(true);

    }//GEN-LAST:event_jButtonTennisActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed

        try {
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File("src\\quizmaster\\click.wav").getAbsoluteFile());
            Clip clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();
        } catch (IOException | LineUnavailableException | UnsupportedAudioFileException ex) {
            System.out.println("Error playing sound file: " + ex.getMessage());
        }

        dispose();

        Topics topics = new Topics();
        topics.setVisible(true);
    }//GEN-LAST:event_jButtonBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonCricket;
    private javax.swing.JButton jButtonFootball;
    private javax.swing.JButton jButtonTennis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
