/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quizmaster;

import java.io.File;
import java.io.IOException;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;

/**
 *
 * @author asifa
 */
public class Topics extends javax.swing.JFrame {

    /**
     * Creates new form Topics
     */
    public Topics() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButtonBack = new javax.swing.JButton();
        jButtonMath = new javax.swing.JButton();
        jButtonIQ = new javax.swing.JButton();
        jButtonSports = new javax.swing.JButton();
        jButtonBangladesh = new javax.swing.JButton();
        jButtonProgramming = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Select  a  Topic");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 330, 30));

        jButtonBack.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(153, 0, 153));
        jButtonBack.setText("BACK");
        jButtonBack.setBorder(null);
        jButtonBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 110, 50));

        jButtonMath.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButtonMath.setForeground(new java.awt.Color(102, 0, 102));
        jButtonMath.setText("Math");
        jButtonMath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMathActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMath, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 170, 30));

        jButtonIQ.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButtonIQ.setForeground(new java.awt.Color(102, 0, 102));
        jButtonIQ.setText("IQ");
        jButtonIQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIQActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 170, 30));

        jButtonSports.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButtonSports.setForeground(new java.awt.Color(102, 0, 102));
        jButtonSports.setText("Sports");
        jButtonSports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSportsActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSports, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 170, 30));

        jButtonBangladesh.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButtonBangladesh.setForeground(new java.awt.Color(102, 0, 102));
        jButtonBangladesh.setText("Bangladesh");
        jButtonBangladesh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBangladeshActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBangladesh, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 170, 30));

        jButtonProgramming.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButtonProgramming.setForeground(new java.awt.Color(102, 0, 102));
        jButtonProgramming.setText("Programming");
        jButtonProgramming.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProgrammingActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonProgramming, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 170, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizmaster/background.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        
        try {
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File("src\\quizmaster\\click.wav").getAbsoluteFile());
            Clip clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();
        } catch (IOException | LineUnavailableException | UnsupportedAudioFileException ex) {
            System.out.println("Error playing sound file: " + ex.getMessage());
        }
        
        dispose();
        
        HomePage home = new HomePage();
        home.setVisible(true);

    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonProgrammingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProgrammingActionPerformed
        try {
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File("src\\quizmaster\\click.wav").getAbsoluteFile());
            Clip clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();
        } catch (IOException | LineUnavailableException | UnsupportedAudioFileException ex) {
            System.out.println("Error playing sound file: " + ex.getMessage());
        }
        dispose();
        
        Programming programming = new Programming();
        programming.setVisible(true);
        
    }//GEN-LAST:event_jButtonProgrammingActionPerformed

    private void jButtonMathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMathActionPerformed
       
        try {
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File("src\\quizmaster\\click.wav").getAbsoluteFile());
            Clip clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();
        } catch (IOException | LineUnavailableException | UnsupportedAudioFileException ex) {
            System.out.println("Error playing sound file: " + ex.getMessage());
        }
        
        dispose();
        Math math = new Math();
        math.setVisible(true);
        
    }//GEN-LAST:event_jButtonMathActionPerformed

    private void jButtonIQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIQActionPerformed
        
        try {
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File("src\\quizmaster\\click.wav").getAbsoluteFile());
            Clip clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();
        } catch (IOException | LineUnavailableException | UnsupportedAudioFileException ex) {
            System.out.println("Error playing sound file: " + ex.getMessage());
        }
        
        dispose();
        
        IQ iq =  new IQ();
        iq.setVisible(true);
        
    }//GEN-LAST:event_jButtonIQActionPerformed

    private void jButtonSportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSportsActionPerformed

        try {
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File("src\\quizmaster\\click.wav").getAbsoluteFile());
            Clip clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();
        } catch (IOException | LineUnavailableException | UnsupportedAudioFileException ex) {
            System.out.println("Error playing sound file: " + ex.getMessage());
        }
        
        dispose();
        Sports sports = new Sports();
        sports.setVisible(true);
        
    }//GEN-LAST:event_jButtonSportsActionPerformed

    private void jButtonBangladeshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBangladeshActionPerformed
        
        try {
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File("src\\quizmaster\\click.wav").getAbsoluteFile());
            Clip clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();
        } catch (IOException | LineUnavailableException | UnsupportedAudioFileException ex) {
            System.out.println("Error playing sound file: " + ex.getMessage());
        }
        
        dispose();
        Bangladesh bd = new Bangladesh();
        bd.setVisible(true);
        
    }//GEN-LAST:event_jButtonBangladeshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Topics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Topics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Topics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Topics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Topics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonBangladesh;
    private javax.swing.JButton jButtonIQ;
    private javax.swing.JButton jButtonMath;
    private javax.swing.JButton jButtonProgramming;
    private javax.swing.JButton jButtonSports;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
